/* Generated by the Englist compiler — do not edit */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

String_t eng_string_new(const char* p);
long eng_string_len(String_t s);
String_t eng_string_concat(String_t a, String_t b);
void eng_string_free(String_t s);
String_t string_new(const char* p);
long length();
String_t concat(String_t other);
void free();
long main();

typedef struct String {
    const char* ptr;
} String_t;


String_t eng_string_new(const char* p) {
}

long eng_string_len(String_t s) {
}

String_t eng_string_concat(String_t a, String_t b) {
}

void eng_string_free(String_t s) {
}

String_t string_new(const char* p) {
    return eng_string_new(p);
}

long length() {
    return eng_string_len(self);
}

String_t concat(String_t other) {
    return eng_string_concat(self, other);
}

void free() {
    eng_string_free(self);
}

int main() {
    long s = string_new("hello world");
    long l = s.length();
    return l;
    return 0;
}

