/* Generated by the Englist compiler — do not edit */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

typedef struct Vector {
    char _empty;
} Vector_t;


Vector_t vector_new();
Vector_t vector_push(Vector_t v, long item);
long vector_get(Vector_t v, long index);
int main();




int main() {
    __auto_type v = vector_new();
    __auto_type v2 = vector_push(v, 42);
    return vector_get(v2, 0);
    return 0;
}

