[package]
name        = "vinglish"
version.workspace    = true
edition.workspace    = true
description = "vng — the Vinglish compiler driver"

[[bin]]
name = "vng"
path = "src/main.rs"

[dependencies]
vinglish-lexer      = { path = "../vinglish-lexer" }
vinglish-parser     = { path = "../vinglish-parser" }
vinglish-types      = { path = "../vinglish-types" }
vinglish-diagnostics= { path = "../vinglish-diagnostics" }
vinglish-codegen    = { path = "../vinglish-codegen" }
vinglish-fmt        = { path = "../vinglish-fmt" }
vinglish-mir        = { path = "../vinglish-mir" }
vinglish-opt        = { path = "../vinglish-opt" }
vinglish-own        = { path = "../vinglish-own" }
vinglish-ssa        = { path = "../vinglish-ssa" }
clap.workspace = true
vinglish-hir = { path = "../vinglish-hir" }
vinglish-analysis = { path = "../vinglish-analysis" }
vinglish-llvm = { path = "../vinglish-llvm" }
vinglish-lsp = { path = "../vinglish-lsp" }
vinglish-ir-export = { path = "../vinglish-ir-export" }
tokio = { version = "1.52.3", features = ["full"] }
vinglish-pkg = { version = "0.2.1", path = "../vinglish-pkg" }

[dev-dependencies]
insta = "1.39.0"
walkdir = "2.4.0"
assert_cmd = "2.0"
