[package]
name = "vinglish-std"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vinglish-bindgen = { path = "../vinglish-bindgen" }
vinglish-codegen = { path = "../vinglish-codegen" }
