use vinglish_parser::ast::*;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum CEmitError {
    #[error("unsupported construct: {0}")]
    Unsupported(String),
    #[error("fmt error: {0}")]
    Fmt(#[from] std::fmt::Error),
}

/// Emit a complete C translation unit for the module.
pub fn emit_c(module: &Module) -> Result<String, CEmitError> {
    let mut emitter = CEmitter::new();
    emitter.emit_module(module)?;
    Ok(emitter.output)
}

thread_local! {
    static FOREIGN_FNS: std::cell::RefCell<std::collections::HashSet<String>> = std::cell::RefCell::new(std::collections::HashSet::new());
}

struct CEmitter {
    output: String,
    indent: usize,
    pointer_vars: std::collections::HashSet<String>,
    current_ret_ty: Option<String>,
}

impl CEmitter {
    fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            pointer_vars: std::collections::HashSet::new(),
            current_ret_ty: None,
        }
    }

    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn line(&mut self, s: &str) {
        let prefix = "    ".repeat(self.indent);
        self.output.push_str(&prefix);
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    fn indent(&mut self) {
        self.indent += 1;
    }
    fn dedent(&mut self) {
        self.indent = self.indent.saturating_sub(1);
    }

    fn emit_module(&mut self, module: &Module) -> Result<(), CEmitError> {
        FOREIGN_FNS.with(|fns| {
            let mut fns = fns.borrow_mut();
            fns.clear();
            for item in &module.items {
                if let Item::Function(f) = item {
                    if f.is_foreign {
                        fns.insert(f.name.name.clone());
                    }
                }
            }
        });
        // Header
        self.emit("/* Generated by the Vinglish compiler — do not edit */\n");
        self.emit("#include <stdio.h>\n");
        self.emit("#include <stdlib.h>\n");
        self.emit("#include <string.h>\n");
        self.emit("#include <math.h>\n");
        self.blank();

        // Type definitions
        for item in &module.items {
            if let Item::Type(t) = item {
                self.emit_type_decl(t)?;
            }
        }
        self.blank();

        // Forward declarations of all functions
        for item in &module.items {
            if let Item::Function(f) = item {
                self.emit_fn_forward(f)?;
            }
        }
        self.blank();

        // Full function definitions
        for item in &module.items {
            match item {
                Item::Function(f) => {
                    self.emit_function(f)?;
                    self.blank();
                }
                Item::Statement(_) => {
                    // Top-level statements go into a synthetic main if there is none
                }
                _ => {}
            }
        }

        // If no main function, wrap top-level statements
        let has_main = module
            .items
            .iter()
            .any(|i| matches!(i, Item::Function(f) if f.name.name == "main"));
        if !has_main {
            let stmts: Vec<&Stmt> = module
                .items
                .iter()
                .filter_map(|i| {
                    if let Item::Statement(s) = i {
                        Some(s)
                    } else {
                        None
                    }
                })
                .collect();
            if !stmts.is_empty() {
                self.emit("int main() {\n");
                self.indent();
                for s in stmts {
                    self.emit_stmt(s)?;
                }
                self.line("return 0;");
                self.dedent();
                self.emit("}\n");
            }
        }

        Ok(())
    }

    fn emit_type_decl(&mut self, t: &TypeDef) -> Result<(), CEmitError> {
        let name = c_ident(&t.name.name);
        self.emit(&format!("typedef struct {} {{\n", name));
        self.indent();
        for field in &t.fields {
            let ty = type_to_c(&field.ty);
            let fname = c_ident(&field.name.name);
            self.line(&format!("{} {};", ty, fname));
        }
        if t.fields.is_empty() {
            self.line("char _empty;");
        }
        self.dedent();
        self.emit(&format!("}} {}_t;\n\n", name));
        Ok(())
    }

    fn emit_fn_forward(&mut self, f: &FunctionDef) -> Result<(), CEmitError> {
        if f.is_foreign {
            let std_fns = [
                "pow", "sin", "cos", "tan", "sqrt", "log", "log10", "exp", "ceil", "floor",
                "round", "puts", "free", "malloc", "print", "println",
            ];
            if std_fns.contains(&f.name.name.as_str()) {
                return Ok(());
            }
        }
        let ret = if f.name.name == "main" {
            "int".to_string()
        } else {
            f.ret_type.as_ref().map(type_to_c).unwrap_or("void".into())
        };
        let params = f
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_c(&p.ty), c_ident(&p.name.name)))
            .collect::<Vec<_>>()
            .join(", ");
        let name = if f.name.name == "main" {
            "main".to_string()
        } else {
            c_ident(&f.name.name)
        };
        self.emit(&format!("{} {}({});\n", ret, name, params));
        Ok(())
    }

    fn emit_function(&mut self, f: &FunctionDef) -> Result<(), CEmitError> {
        if f.is_foreign {
            return Ok(());
        }
        self.pointer_vars.clear();
        for p in &f.params {
            let is_ptr = match &p.ty {
                TypeExpr::Reference { .. } => true,
                TypeExpr::Generic { base, .. } if base.name == "address" => true,
                _ => false,
            };
            if is_ptr {
                self.pointer_vars.insert(c_ident(&p.name.name));
            }
        }
        let ret = if f.name.name == "main" {
            "int".to_string()
        } else {
            f.ret_type.as_ref().map(type_to_c).unwrap_or("void".into())
        };
        self.current_ret_ty = Some(ret.clone());
        let params = f
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_c(&p.ty), c_ident(&p.name.name)))
            .collect::<Vec<_>>()
            .join(", ");
        let name = c_ident(&f.name.name);
        self.emit(&format!("{} {}({}) {{\n", ret, name, params));
        self.indent();
        for stmt in &f.body.stmts {
            self.emit_stmt(stmt)?;
        }
        if f.name.name == "main" {
            self.line("return 0;");
        }
        self.dedent();
        self.emit("}\n");
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), CEmitError> {
        match stmt {
            Stmt::Let(l) => {
                let ty = l.ty.as_ref().map(type_to_c).unwrap_or("__auto_type".into());
                let name = c_ident(&l.name.name);

                let is_ptr = match &l.ty {
                    Some(TypeExpr::Reference { .. }) => true,
                    Some(TypeExpr::Generic { base, .. }) if base.name == "address" => true,
                    _ => {
                        if let Some(val) = &l.value {
                            match val {
                                Expr::Call { callee, .. } => {
                                    if let Expr::Ident(id) = &**callee {
                                        id.name == "ving_alloc"
                                    } else {
                                        false
                                    }
                                }
                                Expr::UnOp {
                                    op: UnOp::Borrow(_),
                                    ..
                                } => true,
                                _ => false,
                            }
                        } else {
                            false
                        }
                    }
                };
                if is_ptr {
                    self.pointer_vars.insert(name.clone());
                }

                if let Some(val) = &l.value {
                    let val_str = self.emit_expr(val)?;
                    self.line(&format!("{} {} = {};", ty, name, val_str));
                } else {
                    self.line(&format!("{} {};", ty, name));
                }
                Ok(())
            }

            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let val_str = self.emit_expr(val)?;
                    self.line(&format!("return {};", val_str));
                } else {
                    self.line("return;");
                }
                Ok(())
            }

            Stmt::If(i) => {
                let cond = self.emit_expr(&i.condition)?;
                self.line(&format!("if ({}) {{", cond));
                self.indent();
                for s in &i.then_block.stmts {
                    self.emit_stmt(s)?;
                }
                self.dedent();
                if let Some(else_block) = &i.otherwise {
                    self.line("} else {");
                    self.indent();
                    for s in &else_block.stmts {
                        self.emit_stmt(s)?;
                    }
                    self.dedent();
                }
                self.line("}");
                Ok(())
            }

            Stmt::When(w) => {
                let cond = self.emit_expr(&w.condition)?;
                self.line(&format!("if ({}) {{", cond));
                self.indent();
                for s in &w.then_block.stmts {
                    self.emit_stmt(s)?;
                }
                self.dedent();
                if let Some(else_block) = &w.otherwise {
                    self.line("} else {");
                    self.indent();
                    for s in &else_block.stmts {
                        self.emit_stmt(s)?;
                    }
                    self.dedent();
                }
                self.line("}");
                Ok(())
            }

            Stmt::Repeat(r) | Stmt::ParallelRepeat(r) => {
                match r {
                    RepeatStmt::While {
                        condition, body, ..
                    } => {
                        let cond = self.emit_expr(condition)?;
                        self.line(&format!("while ({}) {{", cond));
                        self.indent();
                        for s in &body.stmts {
                            self.emit_stmt(s)?;
                        }
                        self.dedent();
                        self.line("}");
                    }
                    RepeatStmt::ForEvery {
                        var,
                        iterable,
                        body,
                        ..
                    } => {
                        // Emit as C for-range over array
                        let iter = self.emit_expr(iterable)?;
                        self.line(&format!("/* repeat for every {} */", var.name));
                        self.line(&format!("for (long _i = 0; _i < _len({}); _i++) {{", iter));
                        self.indent();
                        self.line(&format!(
                            "long {} = _get({}, _i);",
                            c_ident(&var.name),
                            iter
                        ));
                        for s in &body.stmts {
                            self.emit_stmt(s)?;
                        }
                        self.dedent();
                        self.line("}");
                    }
                    RepeatStmt::Count { times, body, .. } => {
                        let n = self.emit_expr(times)?;
                        self.line(&format!("for (long _i = 0; _i < {}; _i++) {{", n));
                        self.indent();
                        for s in &body.stmts {
                            self.emit_stmt(s)?;
                        }
                        self.dedent();
                        self.line("}");
                    }
                }
                Ok(())
            }

            Stmt::Match(m) => {
                let subject = self.emit_expr(&m.subject)?;
                self.line(&format!("/* match {} */", subject));
                let mut first = true;
                for case in &m.cases {
                    let cond = pattern_to_c(&case.pattern, &subject);
                    if first {
                        self.line(&format!("if ({}) {{", cond));
                        first = false;
                    } else {
                        self.line(&format!("}} else if ({}) {{", cond));
                    }
                    self.indent();
                    for s in &case.body.stmts {
                        self.emit_stmt(s)?;
                    }
                    self.dedent();
                }
                if let Some(otherwise) = &m.otherwise {
                    if first {
                        self.line("{");
                    } else {
                        self.line("} else {");
                    }
                    self.indent();
                    for s in &otherwise.stmts {
                        self.emit_stmt(s)?;
                    }
                    self.dedent();
                }
                if !first || m.otherwise.is_some() {
                    self.line("}");
                }
                Ok(())
            }

            Stmt::Assign(a) => {
                let target = self.emit_expr(&a.target)?;
                let val = self.emit_expr(&a.value)?;
                let op = match a.op {
                    AssignOp::Assign => "=",
                    AssignOp::AddAssign => "+=",
                    AssignOp::SubAssign => "-=",
                    AssignOp::MulAssign => "*=",
                    AssignOp::DivAssign => "/=",
                };
                self.line(&format!("{} {} {};", target, op, val));
                Ok(())
            }

            Stmt::Expr(e) => {
                let s = self.emit_expr(e)?;
                self.line(&format!("{};", s));
                Ok(())
            }

            Stmt::Transaction(t) => {
                self.line("/* transaction begin */");
                for s in &t.body.stmts {
                    self.emit_stmt(s)?;
                }
                self.line("/* transaction commit */");
                Ok(())
            }

            _ => Ok(()), // Concurrency stubs — emit comment
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> Result<String, CEmitError> {
        match expr {
            Expr::MacroCall { name, args, .. } => {
                if name.name == "fmt" {
                    // For fmt!, we just emit the first argument as a string for now
                    // In a real implementation this would generate snprintf
                    if let Some(arg) = args.first() {
                        self.emit_expr(arg)
                    } else {
                        Ok("\"\"".to_string())
                    }
                } else {
                    Ok("/* macro call */ 0".to_string())
                }
            }
            Expr::PostfixTry { inner, .. } => self.emit_expr(inner),
            Expr::Lit { value, .. } => Ok(match value {
                Literal::Int(i) => i.to_string(),
                Literal::Float(f) => format!("{:.}", f),
                Literal::Bool(b) => {
                    if *b {
                        "1".into()
                    } else {
                        "0".into()
                    }
                }
                Literal::Text(s) => format!("\"{}\"", s.replace('"', "\\\"").replace('\n', "\\n").replace('\r', "\\r")),
                Literal::Unit => "0".into(),
            }),

            Expr::Ident(id) => Ok(c_ident(&id.name)),
            Expr::GenericInst { base, .. } => Ok(c_ident(&base.name)),

            Expr::Call { callee, args, .. } => {
                let callee_str = self.emit_expr(callee)?;
                let mut arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.emit_expr(a))
                    .collect::<Result<_, _>>()?;
                    
                if callee_str == "Ok" {
                    return Ok(if arg_strs.len() == 1 {
                        arg_strs.pop().unwrap()
                    } else {
                        "0".to_string()
                    });
                } else if callee_str == "Err" {
                    let ret_ty = self.current_ret_ty.clone().unwrap_or_else(|| "long".to_string());
                    return Ok(format!("({}){{0}}", ret_ty));
                }
                
                Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
            }

            Expr::BinOp {
                left, op, right, ..
            } => {
                let l = self.emit_expr(left)?;
                let r = self.emit_expr(right)?;
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq => "==",
                    BinOp::NotEq => "!=",
                    BinOp::Lt | BinOp::IsBelow => "<",
                    BinOp::Gt | BinOp::IsAbove | BinOp::Exceeds => ">",
                    BinOp::LtEq => "<=",
                    BinOp::GtEq => ">=",
                    BinOp::And => "&&",
                    BinOp::Or => "||",
                };
                Ok(format!("({} {} {})", l, op_str, r))
            }

            Expr::UnOp { op, operand, .. } => {
                let inner = self.emit_expr(operand)?;
                let op_str = match op {
                    UnOp::Neg => "-",
                    UnOp::Not => "!",
                    UnOp::Borrow(_) => "&",
                    UnOp::Deref => "*",
                };
                Ok(format!("({}{})", op_str, inner))
            }

            Expr::Field { object, field, .. } => {
                let obj = self.emit_expr(object)?;
                let op = if self.pointer_vars.contains(&obj) {
                    "->"
                } else {
                    "."
                };
                Ok(format!("{}{}{}", obj, op, c_ident(&field.name)))
            }

            Expr::Index { object, index, .. } => {
                let obj = self.emit_expr(object)?;
                let idx = self.emit_expr(index)?;
                Ok(format!("{}[{}]", obj, idx))
            }

            Expr::List { elements, .. } => {
                // Emit as C array literal (simplified — proper heap arrays in Stage 1)
                let elems: Vec<String> = elements
                    .iter()
                    .map(|e| self.emit_expr(e))
                    .collect::<Result<_, _>>()?;
                Ok(format!("{{ {} }}", elems.join(", ")))
            }

            Expr::StructLit { ty, fields, .. } => {
                let name = match &**ty {
                    Expr::Ident(ident) => ident.name.clone(),
                    Expr::GenericInst { base, .. } => base.name.clone(),
                    _ => "unknown".to_string(),
                };
                let fs: Vec<String> = fields
                    .iter()
                    .map(|(id, expr)| {
                        self.emit_expr(expr)
                            .map(|e| format!(".{} = {}", c_ident(&id.name), e))
                    })
                    .collect::<Result<_, _>>()?;
                Ok(format!(
                    "(struct {}){{ {} }}",
                    c_ident(&name),
                    fs.join(", ")
                ))
            }

            Expr::Block(_b) => {
                // Block as expression — emit as statement-expression (GCC extension)
                // or just emit unit for now
                Ok("0".into())
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

fn type_to_c(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Named(id) => match id.name.as_str() {
            "number" | "integer" | "int" => "long".into(),
            "decimal" | "float" => "double".into(),
            "text" | "string" => "const char*".into(),
            "boolean" | "bool" => "int".into(),
            "unit" => "void".into(),
            other => {
                if other.len() == 1 && other.chars().next().unwrap().is_uppercase() {
                    "long".into()
                } else {
                    format!("{}_t", other)
                }
            }
        },
        TypeExpr::List(_) => "void*".into(),
        TypeExpr::Dict { .. } => "void*".into(),
        TypeExpr::Optional(t) => type_to_c(t),
        TypeExpr::Result(t) => type_to_c(t),
        TypeExpr::Generic { base, args } => match base.name.as_str() {
            "List" => "void*".into(),
            "address" => {
                if let Some(arg) = args.first() {
                    format!("{}*", type_to_c(arg))
                } else {
                    "void*".into()
                }
            }
            other => {
                if other.len() == 1 && other.chars().next().unwrap().is_uppercase() {
                    "long".into()
                } else {
                    format!("{}_t", other)
                }
            }
        },
        TypeExpr::Reference { inner, .. } => {
            format!("{}*", type_to_c(inner))
        }
    }
}

fn c_ident(name: &str) -> String {
    // Replace hyphens and spaces with underscores, prefix reserved words
    let safe: String = name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    let is_foreign = FOREIGN_FNS.with(|fns| fns.borrow().contains(name));
    if is_foreign {
        return safe;
    }
    // Avoid C keywords
    match safe.as_str() {
        "int" | "long" | "double" | "void" | "char" | "return" | "if" | "else" | "while"
        | "for" | "switch" | "case" | "break" | "default" | "struct" | "typedef" | "static"
        | "extern" | "free" | "abs" | "puts" | "pow" | "sin" | "cos" | "tan" | "sqrt" | "log"
        | "log10" | "exp" | "ceil" | "floor" | "round" => {
            format!("ving_{}", safe)
        }
        _ => safe,
    }
}

fn pattern_to_c(pat: &Pattern, subject: &str) -> String {
    match pat {
        Pattern::Wildcard(_) | Pattern::Bind(_) => "1".into(),
        Pattern::Constructor(id) => format!("strcmp({}, \"{}\")==0", subject, id.name),
        Pattern::Literal(Literal::Int(i)) => format!("{} == {}", subject, i),
        Pattern::Literal(Literal::Bool(b)) => format!("{} == {}", subject, if *b { 1 } else { 0 }),
        Pattern::Literal(Literal::Text(s)) => format!("strcmp({}, \"{}\")==0", subject, s),
        _ => "1".into(),
    }
}
