[package]
name = "vinglish-analysis"
version.workspace = true
edition.workspace = true

[dependencies]
vinglish-hir = { path = "../vinglish-hir" }
vinglish-mir = { path = "../vinglish-mir" }
vinglish-diagnostics = { path = "../vinglish-diagnostics" }
vinglish-parser = { path = "../vinglish-parser" }
vinglish-lexer = { path = "../vinglish-lexer" }
